// <auto-generated />
using System;
using EFOwned;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFOwned.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190925175721_Recreating")]
    partial class Recreating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFOwned.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("EFOwned.Parent", b =>
                {
                    b.OwnsMany("EFOwned.Child", "Children", b1 =>
                        {
                            b1.Property<Guid>("ParentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ParentId", "Id");

                            b1.ToTable("Child");

                            b1.WithOwner()
                                .HasForeignKey("ParentId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
